apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j40z9n4xz-java-springboot
  janus-idp.io/tekton: j40z9n4xz-java-springboot
  backstage.io/kubernetes-id: j40z9n4xz-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j40z9n4xz-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
